name: Build & Deploy to EC2 (GHCR)

on:
  push:
    branches: ["main"] # 너 레포 기본 브랜치가 main이 아니면 바꿔줘

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Grant execute permission for gradlew
        working-directory: Backend
        run: chmod +x gradlew

      - name: Build jar (skip tests)
        working-directory: Backend
        run: ./gradlew clean build -x test

      - name: Login to GHCR (push)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: Backend
          push: true
          tags: |
            ghcr.io/taeyun-k/runners/be:latest
            ghcr.io/taeyun-k/runners/be:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on EC2 (pull & up)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd ~/app

            # EC2가 private package pull 가능하도록 로그인
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin

            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            docker image prune -f

      - name: Build & push nginx (static web) image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.nginx
          push: true
          tags: |
            ghcr.io/taeyun-k/runners/web:latest
            ghcr.io/taeyun-k/runners/web:${{ github.sha }}
